def second_largest_sum():
    list1 = list()
    n = int(input('Enter the range of list: '))
    for _ in range(n):# O(n)
        number = int(input('Enter a number: '))
        list1.append(number)
    print('Original list:', list1)
    list1.sort() #(n logn)
    print('Sorted list',list1)
    num_3 = list1[-3] #O(1)
    max_num = max(list1) #O(n)
    print(f'Second largest sum: {num_3 + max_num}')
second_largest_sum()
#O(n logn)